# ~/.config/starship.toml
# Doc: https://starship.rs/config/#prompt
# Inserts a blank line between shell prompts
add_newline = true

format = "$all"

command_timeout = 1000 # default 500

[directory]
truncation_length = 100
truncate_to_repo = false
