name: CI

on: [push]

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: apt-get update && apt-get install -y git sudo
      - name: setup dotfiles
        run: .bin/setup
